# Generated by Django 5.2.6 on 2025-10-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sepatu', 'Sepatu'), ('baju', 'Baju'), ('aksesoris', 'Aksesoris'), ('celana', 'Celana')], default='Uncategorized', max_length=50),
        ),
    ]
